"""
All new_arch prompt templates in one file (easy to inspect/audit, per the
approved file tree). Every function that interpolates the raw hate comment
wraps it with safety.wrap_untrusted_text() first (prompt-injection guard -
the comment is data to analyze, never instructions to obey).

Academic honesty note (same as the old project): paper-inspired adaptation,
not exact replication. No prompt is copied word-for-word from any paper.

Persona framing: candidates generated by persona_generator_agent.py are
always professional/expert framings (e.g. "rhetoric analyst", "family
counsellor") - never an identity impersonation of a marginalized group and
never a persona that literally self-describes as "pro-hate". The Prosecutor
PROMPT (build_prosecutor_prompt) is what asks whichever persona was selected
for that role to analytically construct the harmful claim's strongest
internal logic - this is a deliberate, explicit, internal-only exception to
"never argue for the hateful claim", scoped strictly to this one prompt and
never surfaced to the end user (see safety.py).
"""
from safety import wrap_untrusted_text, BASE_SAFETY_RULES

# ---------------------------------------------------------------------------
# 1. Case Analysis Agent
# ---------------------------------------------------------------------------
def build_case_analysis_prompt(comment: str, language_hint: str = None, region_hint: str = None) -> str:
    return f"""You are a hate-speech case analysis agent focused on homophobia and transphobia,
operating across English, Tamil, Basque, Spanish, and Italian.

{wrap_untrusted_text(comment)}

Language hint from caller (may be None/unreliable - verify against the text): {language_hint}
Region hint from caller (manual selection, if any - trust this over any inference): {region_hint}

Analyze the comment for:
- language (en/ta/eu/es/it)
- target_group (e.g. "gay men", "trans women", "LGBT+ people generally")
- hate_category: one of "homophobia", "transphobia", "mixed", "unclear", "unsupported_category"
- intent: list drawn from {{mockery, dehumanization, moral_panic, religious_justification,
  pseudoscientific_claim, family_or_parenting_argument, criminalization, exclusion,
  stereotyping, threat, just_asking_questions, sarcasm, dog_whistle, other}} - not
  restricted to this list if something else fits better
- strategy_hint: list drawn from {{factual_correction, empathy_based_response,
  logical_inconsistency, myth_correction, cultural_contextualization, rights_based_framing,
  harm_reduction, de_escalation, combination}}
- hate_type: "explicit" (overt slur/direct hateful statement) or "implicit" (coded language,
  dog whistle, euphemism, rhetorical question, sarcasm, "just asking questions")
- confidence (0.0-1.0) in this analysis
- hidden_claim: for implicit hate, the underlying claim/assumption being smuggled in (null if explicit/none)
- evidence_topics: list of topics a fact-checker would need to verify (e.g. "adoption outcomes research",
  "historical legal status"); [] if none
- cultural_context_needed (true/false): does answering this well require cultural/regional context?
- safety_notes: anything a downstream writer should be careful about (slurs present, threat language, etc.)
- rationale: 1-3 sentence explanation of the above

{BASE_SAFETY_RULES}
Additional rule for this step: do not repeat slurs or hateful phrases in your own output -
describe them abstractly instead.

Region suggestion (be careful here):
- Only suggest a region/country if the text contains STRONG, EXPLICIT evidence (e.g. a named
  place, a locally-specific law, an explicit self-identification) - not a guess from language,
  name, religion, ethnicity, or generic cultural reference.
- If there is no such strong explicit evidence, set region=null, country=null, confidence=0.0,
  and rationale="no strong explicit regional evidence in the text".
- Never infer a country/region from the language alone (e.g. do not assume Spanish->Spain,
  Tamil->India, English->UK/Ireland - LT-EDI Tamil/English data is Indian, but this must come
  from confirmed dataset/region metadata, never from language choice by itself).

Output JSON only, matching this schema exactly:
{{
  "language": "en",
  "target_group": "...",
  "hate_category": "...",
  "intent": ["..."],
  "strategy_hint": ["..."],
  "hate_type": "explicit",
  "confidence": 0.0,
  "hidden_claim": null,
  "evidence_topics": ["..."],
  "cultural_context_needed": true,
  "region_suggestion": {{"region": null, "country": null, "confidence": 0.0, "rationale": "..."}},
  "safety_notes": ["..."],
  "rationale": "..."
}}"""


# ---------------------------------------------------------------------------
# 2. Persona Generator Agent (fully open-ended, instance-specific)
# ---------------------------------------------------------------------------
def build_persona_generation_prompt(comment: str, case_analysis: dict, candidate_count: int = 7) -> str:
    return f"""You are a persona-design agent. This project addresses homophobic and transphobic
hate speech specifically (sexual-orientation- and gender-identity-based hate) - even if the case
analysis below has an unclear/generic target_group or hate_category, assume this comment falls
within that domain and design personas accordingly, not generically.

Given one specific hate comment and its analysis, invent {candidate_count} DISTINCT, plausible,
professional/expert personas who could meaningfully engage with this exact case. Do NOT draw from
any fixed or generic list - design each persona freshly based on THIS comment's target group,
intent, topic domain, hate category, strategy hints, and cultural context.

Aim for a reasonable MIX across the pool of {candidate_count}: do not make almost all candidates
defender-suited just because rebuttal-oriented experts come to mind more easily. Include at least
2-3 candidates who could plausibly serve as Prosecutor - someone equipped to analytically
articulate/stress-test the harmful claim's internal logic (e.g. a rhetoric analyst, propaganda
historian, extremism researcher, cognitive-bias researcher, debate coach) - not just one, so the
Prosecutor selection below has a genuine choice rather than a single default option.

{wrap_untrusted_text(comment)}

Case analysis:
{case_analysis}

Each persona must be a functional expert role (e.g. a named field/specialty), never an identity
impersonation of a marginalized group, and never framed as personally "for" or "against" the
target group - they are professionals who happen to be well-suited to this case's specific
topic (e.g. if the comment invokes a religious argument, consider a persona versed in
comparative theology or religious-studies rhetoric; if it invokes a pseudoscientific claim,
consider a persona versed in that specific scientific field; if family/parenting framing,
consider a family-studies or child-development specialist; etc).

For each candidate, "name" MUST be a role/title string only - NEVER a personal name, and NEVER
prefixed with an honorific (no "Dr.", "Prof.", "Rev.", "Mr.", "Ms.", etc. followed by a made-up
first/last name). Correct examples: "forensic linguist", "cognitive-behavioral therapist",
"comparative theology scholar", "public health epidemiologist". Incorrect examples (do NOT do
this): "Dr. Michael Green", "Rev. John Harper", "Prof. Lisa Mitchell" - these look like real
people and are never acceptable here, even as placeholders.

Also output: role_type, expertise (list), cultural_relevance (how this persona relates to the
language/region/topic of THIS case), strategy (what approach this persona would take),
relevance_score (0.0-1.0), and suited_for ("prosecutor" | "defender" | "either" - your own
advisory read of which of the two debate roles this persona's expertise fits better;
"prosecutor" means well-suited to analytically surfacing the harmful claim's internal
logic/assumptions for internal stress-testing, "defender" means well-suited to rebutting it
with evidence and cultural awareness).

Then select exactly ONE candidate as the specialized Prosecutor persona and exactly ONE
DIFFERENT candidate as the specialized Defender persona, and explain why each fits this specific
case. The Prosecutor selection should be the persona best equipped to articulate how someone
might sincerely believe/argue the harmful claim (for internal analysis only - this is never
shown to the end user). The Defender selection should be the persona best equipped to rebut it
for this specific audience/language/culture.

{BASE_SAFETY_RULES}

Output JSON only, matching this schema exactly ("name" fields are role titles, e.g.
"forensic linguist" - never a personal name like "Dr. Jane Smith"):
{{
  "candidate_personas": [
    {{"name": "e.g. forensic linguist", "role_type": "...", "expertise": ["..."],
      "cultural_relevance": "...", "strategy": "...", "relevance_score": 0.0, "suited_for": "either"}}
  ],
  "selected_prosecutor": {{"name": "e.g. forensic linguist", "role": "prosecutor", "objective": "...",
      "boundaries": ["stay internal-only", "no gratuitous slurs", "no threats",
                     "no inventing stronger hate than present"]}},
  "selected_defender": {{"name": "e.g. cognitive-behavioral therapist", "role": "defender",
      "objective": "...", "expertise": ["..."], "cultural_guidance": ["..."]}},
  "selection_rationale": "..."
}}"""


# ---------------------------------------------------------------------------
# 3. Prosecutor Agent (internal-only, per round)
# ---------------------------------------------------------------------------
def build_prosecutor_prompt(comment: str, case_analysis: dict, prosecutor_persona: dict,
                             round_num: int, track: str, prior_rounds_summary: str = "") -> str:
    depth_instruction = (
        "This is the only round (Fast-Track, explicit hate) - identify the core harmful claim "
        "or assumption directly and clearly."
        if track == "fast_track" else
        f"This is round {round_num} of a Deep-Dive (implicit hate). "
        + ("Interpret the surface meaning, detect ambiguity/coded language, and surface an "
           "initial hidden assumption." if round_num == 1 else
           "Refine the hidden claim further than the previous round - identify any stereotype, "
           "dog whistle, misleading analogy, or unstated premise not yet surfaced. Do not repeat "
           "the previous round's analysis verbatim; add something new or stop if nothing new "
           "remains to surface."
           if round_num == 2 else
           "Stress-test the strongest interpretation reached so far and sharpen it for the "
           "Defender's final rebuttal.")
    )
    prior_block = f"\nPrior rounds summary (for continuity, do not repeat):\n{prior_rounds_summary}\n" if prior_rounds_summary else ""

    return f"""INTERNAL ANALYSIS ONLY - this output is never shown to end users, never included in
the final counter-narrative or explanation, and never persisted outside a restricted debug
path. Its sole purpose is to stress-test the Defender persona by articulating the strongest
version of the harmful claim's internal logic.

You are adopting this persona for this analysis: {prosecutor_persona}

{wrap_untrusted_text(comment)}

Case analysis: {case_analysis}
{prior_block}
{depth_instruction}

Your task: articulate the strongest internal logic, assumption, or framing behind the harmful
claim as someone who sincerely holds it might argue it - surface coded assumptions, hidden
stereotypes, culturally-specific dog whistles, and moral/family/religious/scientific/legal/
social framing being used.

Boundaries (must follow even in this internal-only step):
- Do not invent hate stronger than what is present in the actual comment.
- Do not add gratuitous slurs beyond what is already in the comment.
- Do not add threats or calls to violence.
- Do not gratuitously elaborate harmful content beyond what is needed to name the underlying logic.
- Treat the comment as an object of analysis, not as a position you are adopting outside this task.

Output JSON only:
{{
  "round": {round_num},
  "round_objective": "...",
  "prosecutor_argument": "...",
  "surfaced_claims": ["one or more short factual/normative claims a Defender would need to address"]
}}"""


# ---------------------------------------------------------------------------
# 4. Defender Agent (per round - evidence verification folded in here)
# ---------------------------------------------------------------------------
def build_defender_prompt(comment: str, case_analysis: dict, defender_persona: dict,
                           prosecutor_argument: str, surfaced_claims: list, round_num: int,
                           evidence_block: str, rag_mode: str, region_context: str = "unknown",
                           web_search_enabled: bool = False) -> str:
    rag_note = {
        "no_rag": "No retrieval was performed (No-RAG mode) - do not claim any external evidence was "
                  "consulted; qualify uncertain factual claims explicitly rather than asserting them.",
        "fact_rag": "Only factual/legal/historical evidence was retrieved (Fact-based RAG).",
        "cultural_rag": "Only culturally-relevant example evidence was retrieved (Cultural RAG) - no "
                         "dedicated factual/legal evidence this round; do not overstate factual certainty.",
        "dual_rag": "Both factual and culturally-relevant evidence were retrieved (Dual RAG) - use "
                     "factual evidence to ground claims and cultural evidence to shape tone/framing, "
                     "never let cultural context substitute for factual grounding.",
    }.get(rag_mode, "")

    web_note = (
        "\nSome evidence below may be marked (origin=web_search, url=...) alongside the local corpus "
        "evidence (origin=local_rag). Web-sourced evidence is NOT automatically reliable: only treat a "
        "web-sourced claim as SUPPORTED if the source URL is identifiable and appears credible (e.g. a "
        "reputable news, educational, governmental, or established organization domain); if the source "
        "is unclear, anonymous, or looks low-quality, treat that claim as NEI rather than SUPPORTED, and "
        "say so in reasoning_summary. Do not treat web evidence as automatically superior or inferior to "
        "local corpus evidence - judge each on its own merits and always note which type of source "
        "(local corpus vs. a named web domain) a supported claim actually relies on."
        if web_search_enabled else ""
    )

    return f"""You are adopting this persona: {defender_persona}

{wrap_untrusted_text(comment)}

Case analysis: {case_analysis}
Region context (confirmed or "unknown" - do not invent one if unknown): {region_context}

The Prosecutor's internal analysis surfaced these claims to address (round {round_num}):
{surfaced_claims}

Retrieved evidence for this round ({rag_mode}): {rag_note}{web_note}
{evidence_block}

Your task, this round:
1. Rebut the surfaced claim(s) directly, using empathy, dignity, rights-based reasoning, and
   logic as appropriate.
2. For each surfaced claim that is a FACTUAL claim (not a pure value judgment), assess it as
   exactly one of: "SUPPORTED", "REFUTED", "NEI" (not enough information) based ONLY on the
   retrieved evidence above - do not treat a merely related passage as proof, and do not
   fabricate evidence or sources. If NEI, qualify the claim rather than asserting or denying it.
3. Use culturally appropriate language for the region context if confirmed; if region is
   "unknown", use culturally neutral language and avoid region-specific claims/analogies.
4. Distinguish clearly (in your own reasoning, not necessarily in the final wording) between
   factual claims and value-based/normative reasoning.

{BASE_SAFETY_RULES}

Output JSON only:
{{
  "defender_response": "the rebuttal/analysis for this round (not the final counter-narrative)",
  "claim_assessments": [
    {{"claim": "...", "verdict": "SUPPORTED", "reasoning_summary": "...", "usable_in_final_cn": true}}
  ],
  "new_information": ["what this round added over prior rounds"],
  "unresolved_questions": ["anything still unclear for the next round or the Judge"],
  "cultural_notes": ["..."],
  "safety_notes": ["..."]
}}"""


# ---------------------------------------------------------------------------
# 5. Evidence claim/query formulation (used by evidence_verifier.py, called
#    from inside the Defender's turn - never a standalone post-hoc stage)
# ---------------------------------------------------------------------------
def build_claim_query_prompt(claim: str, language: str) -> str:
    return f"""Given this factual claim that needs verification: "{claim}"
(the claim originates from a comment/response in language "{language}")

Generate:
1. A retrieval query IN THE ORIGINAL LANGUAGE ({language}) that would find evidence relevant
   to this exact claim.
2. A semantically-equivalent retrieval query IN ENGLISH for the same claim (do not translate
   the claim itself elsewhere - only these two query variants).

Do not assume a country or region from the language - keep both queries topic-focused, not
region-specific, unless the claim itself names a specific place.

Output JSON only:
{{"input_language_query": "...", "english_query": "..."}}"""


# ---------------------------------------------------------------------------
# 6. Judge / Critic Agent (single synthesis, reviews evidence without
#    rerunning a duplicate fact-debate)
# ---------------------------------------------------------------------------
def build_judge_prompt(comment: str, case_analysis: dict, persona_selection: dict,
                        router_decision: dict, debate_rounds: list, region_context: str = "unknown") -> str:
    return f"""You are the Judge/Critic - the sole synthesis step before the final counter-narrative
is written. You review the complete debate (including the internal Prosecutor analysis, which
you may read for context but which must NEVER appear in your final_response_plan or anywhere
that reaches the end user) and produce a plan for the Final Counter-Narrative Agent.

{wrap_untrusted_text(comment)}

Case analysis: {case_analysis}
Persona selection: {persona_selection}
Routing decision: {router_decision}
Region context (confirmed or "unknown"): {region_context}
Complete debate history (internal - includes Prosecutor content for your review only): {debate_rounds}

Assess:
- Relevance to the actual comment and correct interpretation of explicit/implicit hate
- Whether the hidden claim (if implicit) was adequately addressed
- Factual grounding and evidence quality (do not accept unsupported claims as fact)
- Cultural awareness and appropriateness for the region context (or neutral if unknown)
- Safety, non-escalation, and risk of repeating harmful language or amplifying stereotypes
- Logical strength and same-language compliance
- Whether any claims should be rejected (unsupported / unsafe / irrelevant /
  culturally_inappropriate / repetitive) - list each with a reason

Do not simply copy the Defender's response - synthesize your own plan.

IMPORTANT: "selected_language" MUST be exactly the same value as the "language" field already
given above in Case analysis (in this case: "{case_analysis.get('language')}") - this is a fixed
fact already determined upstream, not something for you to re-decide or guess. Copy it exactly,
character for character. Do not default to English or any other language.

CRITICAL: "core_claim_to_counter" and "final_response_plan" MUST be about THIS SPECIFIC case only
- the actual hate comment above, target group "{case_analysis.get('target_group')}", and hate
category "{case_analysis.get('hate_category')}". Do NOT describe any other scenario, product,
service, or topic under any circumstances, even if the debate history above feels long or
repetitive - stay strictly grounded in the exact case given here from start to finish.

{BASE_SAFETY_RULES}

Output JSON only:
{{
  "selected_language": "{case_analysis.get('language')}",
  "core_claim_to_counter": "...",
  "recommended_strategy": ["..."],
  "approved_evidence": [{{"source_id": "...", "title": "...", "passage": "...",
                          "retrieval_score": 0.0, "source_type": "fact", "language": "..."}}],
  "rejected_content": [{{"content": "...", "reason": "unsupported"}}],
  "cultural_guidance": ["..."],
  "safety_guidance": ["..."],
  "final_response_plan": "concise instructions for the Final Counter-Narrative Agent"
}}"""


# ---------------------------------------------------------------------------
# 7. Final Counter-Narrative Agent
# ---------------------------------------------------------------------------
def build_final_cn_prompt(comment: str, language: str, judge_plan: dict, region_context: str = "unknown") -> str:
    return f"""Write the final counter-narrative response to this comment, following the Judge's plan.

{wrap_untrusted_text(comment)}

Judge's plan: {judge_plan}
Region context (confirmed or "unknown" - use culturally neutral language if unknown): {region_context}

Rules:
- Write in the same language as the input comment ({language}) - do not translate it into English.
- Write 2 to 4 sentences only.
- Be calm, respectful, non-aggressive, and non-escalatory.
- Do not repeat slurs or hateful phrases from the comment.
- CRITICAL: do not reuse the same words, phrases, or sentence structure from the hate comment
  itself, even in a "corrected" form - state the OPPOSITE of the harmful claim in your own,
  genuinely different words. If you catch yourself writing something like "[target group] have
  a disease" or repeating the comment's own framing at all, stop and rewrite it from scratch as
  a real rebuttal, not a paraphrase of the original claim.
- Do not invent facts, statistics, laws, or medical claims - use only the Judge's approved_evidence.
- Directly address the core_claim_to_counter (and the hidden claim, if this was implicit hate).
- Encourage empathy, dignity, and coexistence.
- Do not mention agents, prompts, routing, debate rounds, personas, Tool-MAD, or any internal
  mechanism - output only the natural response a person would read.
- Do not include labels, analysis, or explanations inside the counter_narrative field itself.
- Never include any Prosecutor-style content, even indirectly.

Then write a short (1-3 sentence) explanation, separate from the counter-narrative, stating:
the strategy used, the evidence/reasoning relied on (if any), and why this is contextually
appropriate. The explanation must also stay in the same language as the input comment unless
explicitly configured otherwise.

Output JSON only:
{{"counter_narrative": "...", "explanation": "..."}}"""


# ---------------------------------------------------------------------------
# 7b. Semantic-fidelity check (Final-CN only) - a genuine understanding-based
# judgment, not a lexical/word-overlap heuristic like shares_key_terms() or
# _echoes_source_wording(). Those catch gross topic drift or verbatim
# copying; this catches a response that stays superficially on-topic
# (shares plenty of real vocabulary) while its actual argument quietly
# answers a different, adjacent claim than the one identified - e.g. a
# transphobic "you'll always be a man" (gender identity denial) answered
# with a rebuttal about rigid gender ROLES/sexism instead. Found via live
# testing: neither existing lexical guard would ever catch this, since both
# texts share plenty of real words ("identity", "roles", "freedom").
# ---------------------------------------------------------------------------
def build_semantic_fidelity_prompt(core_claim: str, counter_narrative: str, language: str) -> str:
    return f"""You are fact-checking whether a counter-narrative response genuinely and
specifically rebuts ONE claim - not a related-sounding but different one.

The claim the response is supposed to rebut:
{wrap_untrusted_text(core_claim)}

The generated response (in language "{language}"):
{wrap_untrusted_text(counter_narrative)}

Judge whether the response's core argument actually engages with THIS SPECIFIC claim, or
whether it has quietly drifted to a different, adjacent point while still sounding
topically related. Two concrete examples of drift to watch for:
- A claim that DENIES someone's gender identity (e.g. "you'll always be the sex you were
  born") answered with a generic rebuttal about gender ROLE stereotypes/sexism instead of
  gender identity itself - related vocabulary, wrong argument.
- A religious or pseudoscientific justification for hate answered with only generic
  tolerance language that never actually engages the specific religious/scientific claim made.

Sharing related vocabulary is NOT enough for "on_target" - judge the actual substance of what
is being argued, not just the words used.

Output JSON only:
{{"fidelity": "on_target" | "partially_drifted" | "off_target", "reason": "one sentence"}}"""


# ---------------------------------------------------------------------------
# 8. Baseline methods (zero-shot / few-shot / CoT / few-shot+CoT) - simple,
# non-agentic comparison points evaluated alongside the full Prosecutor/
# Defender/Judge pipeline (method="full_pipeline"). These do NOT use RAG,
# personas, or debate - plain single-call generation, for evaluation
# ablation purposes only. See evaluation.py / 07_EVALUATION_STRATEGY.md.
# ---------------------------------------------------------------------------
def build_prompt_zero(comment: str) -> str:
    return f"""Task: Write a counter-narrative response to a homophobic or transphobic comment.

{BASE_SAFETY_RULES}

{wrap_untrusted_text(comment)}

Counter-narrative:"""


def build_prompt_few(comment: str, examples: list) -> str:
    examples_block = "\n\n".join(
        f'Example hate comment: "{h}"\nExample counter-narrative: "{c}"' for h, c in examples
    ) or "(no examples available)"
    return f"""Task: Write a counter-narrative response to a homophobic or transphobic comment.
Below are example (hate comment, counter-narrative) pairs drawn ONLY from the TRAIN split.
Follow the same style and quality - do not copy them verbatim, this is a new comment.

{examples_block}

{BASE_SAFETY_RULES}

{wrap_untrusted_text(comment)}

Counter-narrative:"""


def build_prompt_cot(comment: str) -> str:
    return f"""Task: Write a counter-narrative response to a homophobic or transphobic comment.
Think through it step by step:
Step 1 (Claim): What is the specific harmful claim in this comment?
Step 2 (Target): Who is the target group?
Step 3 (Strategy): What is the best strategy to counter this claim (e.g. factual correction,
empathy, logical inconsistency, myth correction)?
Step 4 (Counter-narrative): Write the actual response, directly addressing the claim from Step 1.

{BASE_SAFETY_RULES}
Keep each step to 1-2 sentences.

{wrap_untrusted_text(comment)}

Now write Steps 1-4 for this comment, then give the final response on a new line starting
exactly with "Counter-narrative:" followed only by the response text (no further labels or
commentary after it)."""


def build_prompt_few_shot_cot(comment: str, examples: list) -> str:
    examples_block = "\n\n".join(
        f'Example hate comment: "{h}"\nExample counter-narrative: "{c}"' for h, c in examples
    ) or "(no examples available)"
    return f"""Task: Write a counter-narrative response to a homophobic or transphobic comment.
Below are example (hate comment, counter-narrative) pairs drawn ONLY from the TRAIN split.
Use them only as style/quality references, not as a template to copy word-for-word.

{examples_block}

Think through it step by step:
Step 1 (Claim): What is the specific harmful claim in this comment?
Step 2 (Target): Who is the target group?
Step 3 (Strategy): What is the best strategy to counter this claim?
Step 4 (Counter-narrative): Write the actual response, directly addressing the claim from Step 1.

{BASE_SAFETY_RULES}
Keep each step to 1-2 sentences.

{wrap_untrusted_text(comment)}

Now write Steps 1-4 for this comment, then give the final response on a new line starting
exactly with "Counter-narrative:" followed only by the response text (no further labels or
commentary after it)."""
